
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: devops
  hosts: webserver
  tasks:
     - name: Transfer executable script script
       copy: src=k8s.yml dest=/home/devops mode=0777
 
     - name: Execute the script
       command: kubectl apply -f k8s.yml
